In [2]:
print("Hello Sundram, how are you?")

Hello Sundram, how are you?

In [3]:
print(100)

100

In [4]:
print("Hello Python, 100, 100.5, True,8")

Hello Python, 100, 100.5, True,8

In [5]:
print("Hello Python", 100, 100.5, True, sep='/')

Hello Python/100/100.5/True

In [6]:
print("Hello Everyone")
print("Hope you all are doing well.")
print("This is our first coding session in Python")

Hello Everyone
Hope you all are doing well.
This is our first coding session in Python

In [ ]:
from typing import Tuple
# Data Structure /Types
1) Number - integer, float, complex
2) string
3) boolean value
4) List
5) Tuple
6) Dictionary
7) Set

In [8]:
int_num = 100
float_num = 100.5
complex_num = 2 + 3j
print(int_num, float_num, complex_num)
print(type(int_num), type(float_num), type(complex_num))

100 100.5 (2+3j)
<class 'int'> <class 'float'> <class 'complex'>

In [9]:
# Text/String
print("Hello Everyone, good evening!")

Hello Everyone, good evening!

In [10]:
print(type("Hello Everyone, good evening!"))

<class 'str'>

In [13]:
print(True)
print(False)
#print(TRUE)
#print(FALSE)

True
False

In [28]:
list1 = [10,10,10,10,12,12,12,14,20,25]
print(list1)
print(type(list1))

tuple1 = (10,10,10,10,12,12,12,14,20,25)
print(tuple1)
print(type(tuple1))

[10, 10, 10, 10, 12, 12, 12, 14, 20, 25]
<class 'list'>
(10, 10, 10, 10, 12, 12, 12, 14, 20, 25)
<class 'tuple'>

In [29]:
list1 = [10,"Sundram",True]
print(list1)
print(type(list1))

[10, 'Sundram', True]
<class 'list'>

In [30]:
list1[-1]

True

In [16]:
list1[1] = 100

In [17]:
list1

[10, 100, 14, 20, 25]

In [19]:
tuple1[1] = 100

TypeError: 'tuple' object does not support item assignment

In [20]:
# set
set1 = {10,10,10,10,10,12,12,12,12,14,20,20,20,25}
print(set1)
print(type(set1))

{20, 25, 10, 12, 14}
<class 'set'>

In [22]:
# Dictionary
print({"name":"Sundram","location":"Bangalore","profession":"GenAI"})

{'name': 'Sundram', 'location': 'Bangalore', 'profession': 'GenAI'}

In [23]:
dict1 = {"name":"Sundram","location":"Bangalore","profession":"GenAI"}

In [25]:
dict1['name'] = "Rahul"

In [26]:
dict1

{'name': 'Rahul', 'location': 'Bangalore', 'profession': 'GenAI'}

# Inputs and Outputs in Python

In [32]:
name = input("Enter your name here :")

salary = int(input("Enter your salary here :"))

double_salary = salary * 2

print(f"Hello {name}")
print(f"Your salary is {salary}")
print(f"Double of your salary is {double_salary}")

Enter your name here :Rohit
Enter your salary here :50000
Hello Rohit
Your salary is 50000
Double of your salary is 100000

In [33]:
# import in python
# https://docs.python.org/3/library/math.html#math.hypot

import math
print(math.pi)

3.141592653589793

In [36]:
# if-else in python
number = int(input("Enter your number here : "))
if number > 0:
  print("Number is positive")
elif number == 0:
  print("Number is zero")
else:
  print("Number is negative")

Enter your number here : -9
Number is negative

In [37]:
email = input("enter your email id here :")
password = input("enter your password here :")

if email =="kumar.s@learnbay.co" and password =='welcome123':
  print("Welcome to LearnBay")
elif email =="kumar.s@learnbay.co" and password !='welcome123':
  print("Incorrect Password")
  password = input("enter your password again :")
  if password =='welcome123':
    print("Finally correct")
  else:
    print("Still incorrect")
else:
  print("Incorrect credentials")

enter your email id here :kumar.s@learnbay.co
enter your password here :welcome12345
Incorrect Password
enter your password again :345654
Still incorrect

In [38]:
email = input("enter your email id here :")
password = input("enter your password here :")

if email =="kumar.s@learnbay.co" and password =='welcome123':
  print("Welcome to LearnBay")
elif email =="kumar.s@learnbay.co" and password !='welcome123':
  print("Incorrect Password")
  password = input("enter your password again :")
  if password =='welcome123':
    print("Finally correct")
  else:
    print("Still incorrect")
else:
  print("Incorrect credentials")

enter your email id here :kumar.s@learnbay.co
enter your password here :welcome12345
Incorrect Password
enter your password again :welcome123
Finally correct

In [40]:
abc = int(input("1st no."))
bcd = int(input("2nd no."))
cde = int(input("3rd no."))

if abc < bcd and abc > cde:
  print("smallest is", abc)
elif bcd < cde:
  print("smallest is", bcd)
else:
  print("smallest is", cde)

1st no.100
2nd no.200
3rd no.120
smallest is 120

In [62]:
import numpy as np
# https://numpy.org/doc/2.3/user/basics.creation.html
import pandas as pd
# https://pandas.pydata.org/docs/user_guide/index.html#user-guide
dataset = pd.read_csv("/content/Titanic-Dataset.csv")
dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [73]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [74]:
dataset = dataset.drop(['PassengerId','Name','Ticket'], axis=1)
dataset.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [42]:
dataset['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [56]:
dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [46]:
dataset['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [52]:
dataset['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [53]:
dataset['Embarked'] = dataset['Embarked'].fillna('S')

In [50]:
#dataset['Embarked'] = np.where(dataset['Embarked']=='', 'S', dataset['Embarked'])

In [54]:
dataset['Embarked'].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [63]:
dataset['Age'] = dataset['Age'].fillna(dataset['Age'].median())

In [57]:
dataset['Age'].describe()

count    891.000000
mean      29.361582
std       13.019697
min        0.420000
25%       22.000000
50%       28.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [64]:
dataset['Age'] = np.where(dataset['Age']<=12,13, dataset['Age'])

In [65]:
dataset['Age'].describe()

count    891.000000
mean      29.998878
std       11.920547
min       13.000000
25%       22.000000
50%       28.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

In [66]:
list1 = [10,10,10,10,12,12,12,14,20,25]
print(list1)
print(type(list1))

[10, 10, 10, 10, 12, 12, 12, 14, 20, 25]
<class 'list'>

In [68]:
list1 + list1

[10,
 10,
 10,
 10,
 12,
 12,
 12,
 14,
 20,
 25,
 10,
 10,
 10,
 10,
 12,
 12,
 12,
 14,
 20,
 25]

In [69]:
array1 = np.array(list1)
print(array1)
print(type(array1))

[10 10 10 10 12 12 12 14 20 25]
<class 'numpy.ndarray'>

In [72]:
array1*5

array([ 50,  50,  50,  50,  60,  60,  60,  70, 100, 125])

In [76]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

# Loops in Python

In [82]:
# while
number = int(input("Enter the number here : "))

i = 1

while i <20:
  print(number, "*", i, "=", number * i)
  i = i+1

Enter the number here : 25
25 * 1 = 25
25 * 2 = 50
25 * 3 = 75
25 * 4 = 100
25 * 5 = 125
25 * 6 = 150
25 * 7 = 175
25 * 8 = 200
25 * 9 = 225
25 * 10 = 250
25 * 11 = 275
25 * 12 = 300
25 * 13 = 325
25 * 14 = 350
25 * 15 = 375
25 * 16 = 400
25 * 17 = 425
25 * 18 = 450
25 * 19 = 475

In [83]:
x = 1
while x < 5:
  print(x)
  x +=1

else:
  print("limit crossed")

1
2
3
4
limit crossed

In [84]:
# For loop function

for i in {1,2,3,4,5}:
  print(i)

1
2
3
4
5

In [85]:
class_student = 10000
for i in range(10,0,-1):
  print(i, class_student)
  class_student = class_student - 0.1*class_student

10 10000
9 9000.0
8 8100.0
7 7290.0
6 6561.0
5 5904.9
4 5314.41
3 4782.969
2 4304.6721
1 3874.20489

In [86]:
for i in range(0,15):
  print("Hello Everyone!")

Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!
Hello Everyone!

In [87]:
def add_two_numbers(a,b):
  return a+b

In [89]:
add_two_numbers(122,489)

611

In [90]:
def is_even_number(num):
  if type(num) == int:
    if num % 2 == 0:
      return "Number is even"
    else:
      return "Number is odd"
  else:
    return "Please enter integer value"

In [95]:
is_even_number(2307/3456)

'Please enter integer value'

In [97]:
is_even_number(0)

'Number is even'

In [98]:
def square(num):
  return num**2
square(99)

9801

In [99]:
id(square)

134453252436064

In [101]:
# lambda function
a = lambda num: num**2

In [102]:
a(99)

9801

In [103]:
def add_two_numbers(a,b):
  return a+b

In [106]:
add_two_numbers(4,5)

9

In [104]:
abc = lambda a,b:a+b

In [105]:
abc(4,5)

9

In [107]:
a = lambda x: 'even' if x%2 == 0 else "odd"
a(100)

'even'

In [108]:
a(103)

'odd'