# Bag of Words

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
text = ["I like food food food food", "I do not like food",'NLP is good for text data']

In [17]:
vectorizer = CountVectorizer(binary=True)

In [18]:
nlp = vectorizer.fit_transform(text)
nlp

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12 stored elements and shape (3, 10)>

In [12]:
nlp.shape

(3, 10)

In [19]:
import pandas as pd
pd.DataFrame(nlp.toarray(),columns=vectorizer.get_feature_names_out())

   data  do  food  for  good  is  like  nlp  not  text
0     0   0     1    0     0   0     1    0    0     0
1     0   1     1    0     0   0     1    0    1     0
2     1   0     0    1     1   1     0    1    0     1

In [11]:
vectorizer.vocabulary_

{'like': 6,
 'food': 2,
 'do': 1,
 'not': 8,
 'nlp': 7,
 'is': 5,
 'good': 4,
 'for': 3,
 'text': 9,
 'data': 0}

# TF-IDF

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
tf_idf = TfidfVectorizer(binary=True)

In [22]:
tf_idf

TfidfVectorizer(binary=True)

In [23]:
tfidf_num = tf_idf.fit_transform(text)

In [24]:
tfidf_num

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12 stored elements and shape (3, 10)>

In [25]:
pd.DataFrame(tfidf_num.toarray(),columns=tf_idf.get_feature_names_out())

       data        do      food  ...       nlp       not      text
0  0.000000  0.000000  0.707107  ...  0.000000  0.000000  0.000000
1  0.000000  0.562829  0.428046  ...  0.000000  0.562829  0.000000
2  0.408248  0.000000  0.000000  ...  0.408248  0.000000  0.408248

[3 rows x 10 columns]

# n-grams

In [28]:
text = ["I like food", "I do not like food",'NLP is good for text data']

In [36]:
tf_idf = TfidfVectorizer(binary=True, ngram_range=(1, 4))
vec_rep = tf_idf.fit_transform(text)
pd.DataFrame(vec_rep.toarray(),columns=tf_idf.get_feature_names_out())

       data        do    do not  ...  not like food      text  text data
0  0.000000  0.000000  0.000000  ...       0.000000  0.000000   0.000000
1  0.000000  0.338348  0.338348  ...       0.338348  0.000000   0.000000
2  0.235702  0.000000  0.000000  ...       0.000000  0.235702   0.235702

[3 rows x 28 columns]

In [37]:
vec_rep.shape

(3, 28)

In [38]:
editorial = "The Supreme Court of India walked a tightrope in its judgment delivered on September 15, 2025, on the Waqf (Amendment) Act, 2025, which amended the 1995 Waqf Act to regulate Muslim religious endowments, including vast land holdings across India. The Court put several controversial provisions on hold but refused to freeze the entire Act on grounds of constitutionality and other concerns. This turned out to be a rare instance where supporters and critics of the Act claimed vindication for their respective positions in the Court’s order. The government views the amendments as necessary to curb the alleged misuse and corruption under the earlier Waqf Act, while critics, including the Congress, see it as arbitrary interference in the affairs of the Muslim community. The Court has now stayed the requirement that only Muslims practising for five years can create waqf, and the power vested in District Collectors to adjudicate waqf property disputes. It also capped non-Muslim members to four in the Central Waqf Council and three in State Boards, down from potentially 12 and seven, respectively. The Court also directed that CEOs of Waqf Boards should preferably be Muslims. The removal of the provision for waqf-by-user recognition in the amended law has been upheld as valid by the Court, with the caveat that waqf properties registered as on April 8, 2025, under such a claim remain protected. Restrictions on waqf status for protected monuments and tribal lands were deemed constitutionally valid."

In [60]:
editorial

'The Supreme Court of India walked a tightrope in its judgment delivered on September 15, 2025, on the Waqf (Amendment) Act, 2025, which amended the 1995 Waqf Act to regulate Muslim religious endowments, including vast land holdings across India. The Court put several controversial provisions on hold but refused to freeze the entire Act on grounds of constitutionality and other concerns. This turned out to be a rare instance where supporters and critics of the Act claimed vindication for their respective positions in the Court’s order. The government views the amendments as necessary to curb the alleged misuse and corruption under the earlier Waqf Act, while critics, including the Congress, see it as arbitrary interference in the affairs of the Muslim community. The Court has now stayed the requirement that only Muslims practising for five years can create waqf, and the power vested in District Collectors to adjudicate waqf property disputes. It also capped non-Muslim members to four in the Central Waqf Council and three in State Boards, down from potentially 12 and seven, respectively. The Court also directed that CEOs of Waqf Boards should preferably be Muslims. The removal of the provision for waqf-by-user recognition in the amended law has been upheld as valid by the Court, with the caveat that waqf properties registered as on April 8, 2025, under such a claim remain protected. Restrictions on waqf status for protected monuments and tribal lands were deemed constitutionally valid.'

In [46]:
import nltk
from nltk import word_tokenize, sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [50]:
sent_tokenize(editorial)

['The Supreme Court of India walked a tightrope in its judgment delivered on September 15, 2025, on the Waqf (Amendment) Act, 2025, which amended the 1995 Waqf Act to regulate Muslim religious endowments, including vast land holdings across India.',
 'The Court put several controversial provisions on hold but refused to freeze the entire Act on grounds of constitutionality and other concerns.',
 'This turned out to be a rare instance where supporters and critics of the Act claimed vindication for their respective positions in the Court’s order.',
 'The government views the amendments as necessary to curb the alleged misuse and corruption under the earlier Waqf Act, while critics, including the Congress, see it as arbitrary interference in the affairs of the Muslim community.',
 'The Court has now stayed the requirement that only Muslims practising for five years can create waqf, and the power vested in District Collectors to adjudicate waqf property disputes.',
 'It also capped non-Muslim members to four in the Central Waqf Council and three in State Boards, down from potentially 12 and seven, respectively.',
 'The Court also directed that CEOs of Waqf Boards should preferably be Muslims.',
 'The removal of the provision for waqf-by-user recognition in the amended law has been upheld as valid by the Court, with the caveat that waqf properties registered as on April 8, 2025, under such a claim remain protected.',
 'Restrictions on waqf status for protected monuments and tribal lands were deemed constitutionally valid.']

In [47]:
word_tokenize(editorial)

['The',
 'Supreme',
 'Court',
 'of',
 'India',
 'walked',
 'a',
 'tightrope',
 'in',
 'its',
 'judgment',
 'delivered',
 'on',
 'September',
 '15',
 ',',
 '2025',
 ',',
 'on',
 'the',
 'Waqf',
 '(',
 'Amendment',
 ')',
 'Act',
 ',',
 '2025',
 ',',
 'which',
 'amended',
 'the',
 '1995',
 'Waqf',
 'Act',
 'to',
 'regulate',
 'Muslim',
 'religious',
 'endowments',
 ',',
 'including',
 'vast',
 'land',
 'holdings',
 'across',
 'India',
 '.',
 'The',
 'Court',
 'put',
 'several',
 'controversial',
 'provisions',
 'on',
 'hold',
 'but',
 'refused',
 'to',
 'freeze',
 'the',
 'entire',
 'Act',
 'on',
 'grounds',
 'of',
 'constitutionality',
 'and',
 'other',
 'concerns',
 '.',
 'This',
 'turned',
 'out',
 'to',
 'be',
 'a',
 'rare',
 'instance',
 'where',
 'supporters',
 'and',
 'critics',
 'of',
 'the',
 'Act',
 'claimed',
 'vindication',
 'for',
 'their',
 'respective',
 'positions',
 'in',
 'the',
 'Court',
 '’',
 's',
 'order',
 '.',
 'The',
 'government',
 'views',
 'the',
 'amendments',
 'as',
 'necessary',
 'to',
 'curb',
 'the',
 'alleged',
 'misuse',
 'and',
 'corruption',
 'under',
 'the',
 'earlier',
 'Waqf',
 'Act',
 ',',
 'while',
 'critics',
 ',',
 'including',
 'the',
 'Congress',
 ',',
 'see',
 'it',
 'as',
 'arbitrary',
 'interference',
 'in',
 'the',
 'affairs',
 'of',
 'the',
 'Muslim',
 'community',
 '.',
 'The',
 'Court',
 'has',
 'now',
 'stayed',
 'the',
 'requirement',
 'that',
 'only',
 'Muslims',
 'practising',
 'for',
 'five',
 'years',
 'can',
 'create',
 'waqf',
 ',',
 'and',
 'the',
 'power',
 'vested',
 'in',
 'District',
 'Collectors',
 'to',
 'adjudicate',
 'waqf',
 'property',
 'disputes',
 '.',
 'It',
 'also',
 'capped',
 'non-Muslim',
 'members',
 'to',
 'four',
 'in',
 'the',
 'Central',
 'Waqf',
 'Council',
 'and',
 'three',
 'in',
 'State',
 'Boards',
 ',',
 'down',
 'from',
 'potentially',
 '12',
 'and',
 'seven',
 ',',
 'respectively',
 '.',
 'The',
 'Court',
 'also',
 'directed',
 'that',
 'CEOs',
 'of',
 'Waqf',
 'Boards',
 'should',
 'preferably',
 'be',
 'Muslims',
 '.',
 'The',
 'removal',
 'of',
 'the',
 'provision',
 'for',
 'waqf-by-user',
 'recognition',
 'in',
 'the',
 'amended',
 'law',
 'has',
 'been',
 'upheld',
 'as',
 'valid',
 'by',
 'the',
 'Court',
 ',',
 'with',
 'the',
 'caveat',
 'that',
 'waqf',
 'properties',
 'registered',
 'as',
 'on',
 'April',
 '8',
 ',',
 '2025',
 ',',
 'under',
 'such',
 'a',
 'claim',
 'remain',
 'protected',
 '.',
 'Restrictions',
 'on',
 'waqf',
 'status',
 'for',
 'protected',
 'monuments',
 'and',
 'tribal',
 'lands',
 'were',
 'deemed',
 'constitutionally',
 'valid',
 '.']

# Stopwords

In [51]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [59]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
print(stop_words)
print(len(stop_words))

{"we've", 'his', 'their', 'just', 'out', "they've", 'other', 'through', 'my', 'again', 'only', 'very', 'before', 'now', 'until', 've', 'yourselves', 'for', 'from', 'been', 'more', 'once', 'is', "she'd", 'will', 'on', 'shan', 'y', 'because', 'being', 'can', 'won', "it'll", "it's", "hadn't", 'isn', "shan't", "aren't", 'same', "won't", 'shouldn', 'wasn', "wasn't", "don't", 'mightn', 'should', 'him', 'nor', 'here', "you'll", 'above', "weren't", 'few', 'under', 'too', 'mustn', 'with', 's', 'had', 'are', 'between', 'than', 'after', 'does', 'there', 'whom', "isn't", 'if', 'into', 'so', 'yourself', 'doesn', "you've", 'at', 'didn', 'ma', 'that', "they'll", 'her', 'no', 'be', 'we', "mightn't", 'what', 'were', "mustn't", "didn't", 'do', 'further', 're', 'haven', 'has', 'itself', 'themselves', "couldn't", 'down', 'own', 'below', 'against', 'them', 'then', "i'll", 'ours', 'they', "we'd", 'a', 'he', 'theirs', 'where', 'd', 'both', 'during', "we'll", "we're", "i'd", 'ain', 'doing', 'did', "haven't", 'was', 'and', 'o', "it'd", "he'll", 'those', 'your', 'an', 'some', 'how', 'all', "he's", 'myself', 'of', 'our', 't', 'she', 'up', 'off', 'which', "i'm", 'who', "should've", 'aren', "she'll", "needn't", 'why', 'you', 'most', 'when', 'not', 'any', 'it', 'as', "shouldn't", 'each', 'm', 'these', "i've", "she's", 'am', "you'd", 'hers', "wouldn't", 'this', "doesn't", "he'd", 'the', 'herself', 'me', 'by', 'hasn', 'but', 'll', 'ourselves', 'yours', 'or', 'while', 'its', 'to', 'such', 'weren', 'couldn', 'don', "that'll", 'having', 'over', "they'd", 'hadn', "they're", 'himself', "hasn't", 'needn', 'wouldn', "you're", 'have', 'in', 'i', 'about'}
198

In [62]:
set(stopwords.words('hinglish'))

{'hopefully',
 'noone',
 'regardless',
 'according',
 'might',
 'shouldnt',
 'took',
 'tak',
 'see',
 'their',
 'wali',
 'least',
 'thence',
 'certain',
 'kahin',
 'came',
 'through',
 'downwards',
 'karungi',
 'vaisa',
 'hota',
 'said',
 'tu',
 'dwara',
 'lagte',
 'vali',
 'wherein',
 'teeno',
 'nobody',
 'for',
 'more',
 'batao',
 'new',
 'ok',
 'rahe',
 'better',
 'teesra',
 'on',
 'shan',
 'thanks',
 'y',
 'because',
 'yeh',
 'won',
 "it'll",
 'liye',
 'unless',
 'isn',
 'another',
 "shan't",
 'chahiye',
 'inho',
 "won't",
 'hamara',
 'neither',
 'yup',
 'huye',
 'whereupon',
 'well',
 'kabhi',
 'mightn',
 "let's",
 'nor',
 'wont',
 'k',
 'arre',
 'look',
 'yes',
 'bahut',
 'idk',
 'ki',
 "that's",
 'dono',
 'upon',
 "weren't",
 'jitna',
 'jis',
 'mean',
 'are',
 'baad',
 'chal',
 'does',
 'there',
 'accha',
 'bani',
 'kino',
 'jitne',
 'nd',
 'yourself',
 'havent',
 'rakhe',
 'kisko',
 "you've",
 'at',
 'karenge',
 'using',
 'hi',
 'kitne',
 'rakhen',
 'gaye',
 'mano',
 'karegi',
 'lol',
 'everybody',
 "mightn't",
 'teen',
 'jo',
 'thereupon',
 'were',
 'uss',
 "didn't",
 'hua',
 'jinhone',
 "what's",
 'aur',
 'kara',
 'thus',
 'lekin',
 'down',
 'own',
 'dega',
 'nahin',
 'thorough',
 'boli',
 'uske',
 "who's",
 'try',
 'below',
 'abe',
 'apne',
 'thinking',
 'de',
 'wagaira',
 'thats',
 'against',
 'har',
 'banda',
 'banaya',
 'nothing',
 'poora',
 "we've",
 'honi',
 'seemed',
 'vale',
 'chhaiye',
 'sakta',
 'he',
 'ie',
 'hoga',
 'thru',
 'cannot',
 'thi',
 'where',
 'jinn',
 "here's",
 'sath',
 'thereafter',
 'yet',
 "we're",
 "i'd",
 'kaise',
 'mjhe',
 'dwaara',
 'mainly',
 'really',
 'waha',
 'was',
 'yahan',
 'nhi',
 'those',
 'got',
 'your',
 'around',
 'humne',
 'bolta',
 'keeps',
 'phla',
 'bht',
 'teri',
 'inn',
 'bheetar',
 'who',
 'diyaa',
 'vaisi',
 'mai',
 'whatever',
 'third',
 'teesri',
 'doosre',
 'dede',
 'tell',
 'any',
 'rahi',
 'as',
 'krna',
 'goes',
 'kyuki',
 'm',
 'karna',
 'par',
 'sakte',
 'dekhe',
 'hogi',
 'phle',
 'karke',
 'unhone',
 'secondly',
 'alag',
 'vaala',
 'abbey',
 'later',
 'seem',
 'the',
 'herself',
 'ye',
 'kon',
 'but',
 'sang',
 'wants',
 'know',
 'kaha',
 'karu',
 'huh',
 'jabh',
 'teesre',
 'yours',
 'cant',
 'or',
 'rather',
 'wale',
 'wo',
 'haan',
 'hello',
 'normally',
 'weren',
 'regards',
 'getting',
 'anything',
 "that'll",
 'aapne',
 'rhaa',
 'bilkul',
 'bole',
 "they'd",
 'nai',
 'himself',
 'kinn',
 'somehow',
 'degi',
 'unto',
 'whole',
 'needn',
 'anyone',
 'saktaa',
 'wagerah',
 'second',
 'have',
 'although',
 'etc',
 'ek',
 'about',
 'i',
 'inki',
 'issi',
 'kull',
 'kyunki',
 'apart',
 'waala',
 'tried',
 'mightnt',
 'let',
 'since',
 'andar',
 'edu',
 'kinhe',
 'per',
 'kiye',
 'dijiye',
 'seeing',
 "they've",
 'going',
 'along',
 'herein',
 'kahi',
 'again',
 'hereafter',
 'kul',
 'gotten',
 'many',
 'ones',
 'example',
 'jiski',
 'com',
 'aisi',
 'denge',
 'very',
 'before',
 'ever',
 'even',
 'somebody',
 'ltd',
 'theres',
 'whereafter',
 'iski',
 'seen',
 'please',
 'unkaa',
 'once',
 'saath',
 'beside',
 'karta',
 'three',
 'yah',
 'is',
 'seven',
 'unho',
 'selves',
 'mostly',
 'actually',
 'exactly',
 'else',
 'karti',
 "it's",
 'unka',
 'various',
 'yahi',
 'jinka',
 'already',
 'enough',
 'dusre',
 'sub',
 'shouldn',
 'others',
 'insofar',
 'everyone',
 'wasnt',
 'bata',
 'unlikely',
 'should',
 'him',
 "there's",
 'hadnt',
 'ap',
 'hain',
 'dunga',
 'inkaa',
 'saw',
 'karega',
 'ise',
 'above',
 'bolo',
 'jahan',
 'doosra',
 'hongi',
 'pehla',
 'whom',
 'li',
 'moreover',
 'isse',
 'yeah',
 'asking',
 'didn',
 'bhi',
 'dekhi',
 'every',
 'lagta',
 'would',
 'that',
 'anywhere',
 'vaale',
 'hamne',
 'neeche',
 'hai',
 'bandi',
 'tho',
 'unhe',
 'waisi',
 'accordingly',
 'across',
 'isne',
 "mustn't",
 'do',
 'wahan',
 'bas',
 'usse',
 'maana',
 'cause',
 'has',
 'likely',
 'themselves',
 'bolte',
 'get',
 'kiski',
 'brief',
 "couldn't",
 'rhi',
 'tab',
 'jata',
 'ri',
 'jab',
 'thought',
 'wagairah',
 'kch',
 'done',
 'overall',
 'kahaa',
 'kuch',
 'thik',
 'si',
 'anyhow',
 'looks',
 'much',
 'banae',
 'unko',
 'then',
 'ours',
 'kam',
 'itna',
 'kinki',
 'they',
 'naa',
 'que',
 'a',
 'aside',
 'mil',
 'hereby',
 'unse',
 'howbeit',
 'kahte',
 'meanwhile',
 'd',
 'quite',
 'could',
 'kiska',
 'eg',
 'did',
 "haven't",
 'kal',
 'mani',
 'acha',
 'inner',
 'bola',
 'yaha',
 'an',
 'dvaara',
 'inka',
 'myself',
 'our',
 'sure',
 'of',
 'which',
 'she',
 'whence',
 'want',
 'hm',
 'yehi',
 'baar',
 'kept',
 'thank',
 "needn't",
 'why',
 'gayi',
 'when',
 'jaisa',
 'lately',
 'not',
 'six',
 'it',
 'bana',
 'kafi',
 'hun',
 'han',
 'di',
 'these',
 'old',
 "i've",
 'saying',
 "she's",
 'bhai',
 'waali',
 'am',
 'vo',
 'able',
 'hers',
 'seriously',
 "ain't",
 "wouldn't",
 'inasmuch',
 "can't",
 'this',
 'hasn',
 'whereby',
 'liked',
 'll',
 'rakh',
 'followed',
 'poori',
 'kaisi',
 'truly',
 'near',
 'plus',
 'pura',
 'nahi',
 'someone',
 'koi',
 'neednt',
 'usually',
 'jinhi',
 'couldn',
 'achcha',
 'hoge',
 'un',
 'kaun',
 'non',
 'having',
 'over',
 'tumhare',
 'aata',
 'becomes',
 'le',
 'use',
 'banai',
 'mustnt',
 'allow',
 'sab',
 'next',
 'elsewhere',
 'ghar',
 'take',
 'anyways',
 'sensible',
 'novel',
 'best',
 'kya',
 'almost',
 'his',
 'mera',
 'just',
 'hona',
 'out',
 'rahaa',
 'still',
 'whose',
 'kisne',
 'other',
 'um',
 'apnaa',
 'kaisa',
 'kitno',
 'yourselves',
 've',
 'unke',
 'gone',
 'khud',
 'maybe',
 'ke',
 'name',
 'like',
 'maane',
 'karen',
 'two',
 'avum',
 'will',
 'bol',
 'jaha',
 'besides',
 "c'mon",
 'apni',
 'jaa',
 'toh',
 'went',
 'kyun',
 'apna',
 'jinki',
 'q',
 'wasn',
 'sahi',
 'otherwise',
 "don't",
 'theek',
 'wahaan',
 'sometimes',
 'jidhar',
 'clearly',
 'hoti',
 'often',
 'gives',
 "you'll",
 'one',
 'jinhe',
 'tarah',
 'too',
 'dhang',
 'log',
 'mustn',
 'come',
 's',
 'none',
 'tends',
 'kehte',
 'maano',
 'than',
 'after',
 'main',
 'lagti',
 'if',
 'into',
 'isnt',
 'iska',
 'upar',
 'itne',
 'however',
 'inse',
 'humein',
 'bhitar',
 'oh',
 'waise',
 'lunga',
 'doesn',
 'honge',
 'ya',
 'wahin',
 'chalega',
 'mane',
 'itno',
 'keep',
 'huyi',
 'be',
 'true',
 'merely',
 'dvara',
 'what',
 'kisliye',
 'kinko',
 'kar',
 'kiske',
 'waisa',
 'ko',
 'say',
 'sabse',
 'haven',
 'thoda',
 'hum',
 'mana',
 'tumhari',
 'thoroughly',
 'bad',
 'way',
 'hmm',
 'dusra',
 'twice',
 'everything',
 'dont',
 'isi',
 'reasonably',
 'jin',
 'afterwards',
 'unhi',
 'jiss',
 'sup',
 'them',
 "i'll",
 'something',
 'furthermore',
 'iss',
 'may',
 'vahi',
 'greetings',
 'aadi',
 'kinho',
 'aye',
 'gets',
 "we'd",
 'bande',
 'se',
 'yahaan',
 'okay',
 'kari',
 'mere',
 'tere',
 'both',
 'during',
 'tabh',
 'doing',
 'hu',
 'saare',
 'o',
 'alone',
 'karunga',
 'seeming',
 'rha',
 'unn',
 'some',
 'how',
 'lekar',
 "he's",
 'abhi',
 'dude',
 't',
 'pata',
 'banaye',
 "i'm",
 'logon',
 'werent',
 'puri',
 'aren',
 'honaa',
 "should've",
 'you',
 'uska',
 'rakho',
 'didnt',
 'hote',
 'jinke',
 'bohot',
 'chaiye',
 'kyaa',
 'says',
 'wherever',
 'each',
 'hamari',
 'jaisi',
 'jisme',
 'rehte',
 'somewhat',
 'inhi',
 'banao',
 'vala',
 'bc',
 'dusri',
 'jiske',
 'thodi',
 'keh',
 'hue',
 'known',
 'nope',
 'by',
 'kuchch',
 'certainly',
 'jyaada',
 'jahaan',
 'tum',
 'perhaps',
 'aint',
 'kitni',
 'apan',
 'such',
 'ab',
 'inke',
 'mein',
 'vaali',
 'karne',
 'serious',
 'aise',
 'hasnt',
 'help',
 'within',
 'jiska',
 'pehle',
 'hadn',
 'abbe',
 'karni',
 'kisi',
 "they're",
 'ka',
 'without',
 'ne',
 'aaya',
 'kinke',
 'na',
 "hasn't",
 'allows',
 'ask',
 'trying',
 'kahan',
 'in',
 'tune',
 'thanx',
 'becoming',
 'hotaa',
 'yahin',
 'kiya',
 'usne',
 'kine',
 'causes',
 'used',
 'hereupon',
 'woh',
 'maani',
 'diye',
 'diyo',
 'aisa',
 'given',
 'banayi',
 'usi',
 'anyway',
 'my',
 'rakha',
 'maan',
 'magar',
 'isme',
 'whenever',
 'only',
 'go',
 'now',
 'tujhe',
 'until',
 'from',
 'been',
 'became',
 'dekho',
 'lo',
 'jise',
 'several',
 'tera',
 'fifth',
 'kahaan',
 'must',
 'whoever',
 'being',
 'ex',
 'can',
 'follows',
 'iskaa',
 'beyond',
 'become',
 'kinka',
 "hadn't",
 'th',
 "aren't",
 'inc',
 'ityaadi',
 'kin',
 'looking',
 'maine',
 'sakti',
 'same',
 'whereas',
 "where's",
 "wasn't",
 'mujhe',
 'meri',
 'vahan',
 'less',
 'aap',
 'kayi',
 'people',
 'here',
 'hoyenge',
 'few',
 'ought',
 'diya',
 'umm',
 'under',
 'placed',
 'yadi',
 'together',
 'with',
 'either',
 'via',
 'had',
 'hamare',
 'between',
 'onto',
 'five',
 'raha',
 'sometime',
 'kaafi',
 'inward',
 "isn't",
 'so',
 'jisse',
 'ja',
 'nearly',
 'sara',
 'phli',
 'kab',
 'behind',
 'think',
 'forth',
 'uses',
 'nowhere',
 'taken',
 'willing',
 "they'll",
 'ussi',
 'her',
 'bane',
 'no',
 'lest',
 'hence',
 'following',
 'toward',
 'tjhe',
 'hadd',
 'couldnt',
 'karo',
 'rakhi',
 'we',
 'jayega',
 'appear',
 'thing',
 'good',
 'ho',
 'wohi',
 'soch',
 'further',
 're',
 'useful',
 'mat',
 'itself',
 'btw',
 'jitni',
 'seems',
 'namely',
 'soon',
 'waale',
 'wahi',
 'whether',
 'beforehand',
 'hardly',
 'aya',
 'four',
 'inhe',
 'kuchh',
 'tries',
 'everywhere',
 'itni',
 'ityadi',
 'hoyengi',
 'thereby',
 'knows',
 'agar',
 'eight',
 'koyi',
 'krne',
 'outside',
 'self',
 'throughout',
 'theirs',
 'bro',
 'though',
 'tumhara',
 'wouldnt',
 'shant',
 'dungi',
 "we'll",
 'shall',
 'ain',
 'happens',
 'among',
 'sa',
 'karte',
 'kare',
 'kitna',
 'and',
 "it'd",
 'therein',
 'therefore',
 'all',
 'dekha',
 'anybody',
 'regarding',
 'up',
 'imo',
 'off',
 'except',
 'viz',
 'naah',
 'fir',
 'pehli',
 'most',
 'amongst',
 'nine',
 'jyada',
 'sabhi',
 'comes',
 "shouldn't",
 'needs',
 'jinho',
 'hone',
 'obviously',
 'far',
 'bolti',
 "you'd",
 'wala',
 'aati',
 'provides',
 "doesn't",
 'vahin',
 'also',
 'karun',
 'last',
 'right',
 'me',
 'vaise',
 'saara',
 'us',
 'tha',
 'vahaan',
 ...}

In [63]:
editorial

'The Supreme Court of India walked a tightrope in its judgment delivered on September 15, 2025, on the Waqf (Amendment) Act, 2025, which amended the 1995 Waqf Act to regulate Muslim religious endowments, including vast land holdings across India. The Court put several controversial provisions on hold but refused to freeze the entire Act on grounds of constitutionality and other concerns. This turned out to be a rare instance where supporters and critics of the Act claimed vindication for their respective positions in the Court’s order. The government views the amendments as necessary to curb the alleged misuse and corruption under the earlier Waqf Act, while critics, including the Congress, see it as arbitrary interference in the affairs of the Muslim community. The Court has now stayed the requirement that only Muslims practising for five years can create waqf, and the power vested in District Collectors to adjudicate waqf property disputes. It also capped non-Muslim members to four in the Central Waqf Council and three in State Boards, down from potentially 12 and seven, respectively. The Court also directed that CEOs of Waqf Boards should preferably be Muslims. The removal of the provision for waqf-by-user recognition in the amended law has been upheld as valid by the Court, with the caveat that waqf properties registered as on April 8, 2025, under such a claim remain protected. Restrictions on waqf status for protected monuments and tribal lands were deemed constitutionally valid.'

In [64]:
mywords = word_tokenize(editorial)
mywords

['The',
 'Supreme',
 'Court',
 'of',
 'India',
 'walked',
 'a',
 'tightrope',
 'in',
 'its',
 'judgment',
 'delivered',
 'on',
 'September',
 '15',
 ',',
 '2025',
 ',',
 'on',
 'the',
 'Waqf',
 '(',
 'Amendment',
 ')',
 'Act',
 ',',
 '2025',
 ',',
 'which',
 'amended',
 'the',
 '1995',
 'Waqf',
 'Act',
 'to',
 'regulate',
 'Muslim',
 'religious',
 'endowments',
 ',',
 'including',
 'vast',
 'land',
 'holdings',
 'across',
 'India',
 '.',
 'The',
 'Court',
 'put',
 'several',
 'controversial',
 'provisions',
 'on',
 'hold',
 'but',
 'refused',
 'to',
 'freeze',
 'the',
 'entire',
 'Act',
 'on',
 'grounds',
 'of',
 'constitutionality',
 'and',
 'other',
 'concerns',
 '.',
 'This',
 'turned',
 'out',
 'to',
 'be',
 'a',
 'rare',
 'instance',
 'where',
 'supporters',
 'and',
 'critics',
 'of',
 'the',
 'Act',
 'claimed',
 'vindication',
 'for',
 'their',
 'respective',
 'positions',
 'in',
 'the',
 'Court',
 '’',
 's',
 'order',
 '.',
 'The',
 'government',
 'views',
 'the',
 'amendments',
 'as',
 'necessary',
 'to',
 'curb',
 'the',
 'alleged',
 'misuse',
 'and',
 'corruption',
 'under',
 'the',
 'earlier',
 'Waqf',
 'Act',
 ',',
 'while',
 'critics',
 ',',
 'including',
 'the',
 'Congress',
 ',',
 'see',
 'it',
 'as',
 'arbitrary',
 'interference',
 'in',
 'the',
 'affairs',
 'of',
 'the',
 'Muslim',
 'community',
 '.',
 'The',
 'Court',
 'has',
 'now',
 'stayed',
 'the',
 'requirement',
 'that',
 'only',
 'Muslims',
 'practising',
 'for',
 'five',
 'years',
 'can',
 'create',
 'waqf',
 ',',
 'and',
 'the',
 'power',
 'vested',
 'in',
 'District',
 'Collectors',
 'to',
 'adjudicate',
 'waqf',
 'property',
 'disputes',
 '.',
 'It',
 'also',
 'capped',
 'non-Muslim',
 'members',
 'to',
 'four',
 'in',
 'the',
 'Central',
 'Waqf',
 'Council',
 'and',
 'three',
 'in',
 'State',
 'Boards',
 ',',
 'down',
 'from',
 'potentially',
 '12',
 'and',
 'seven',
 ',',
 'respectively',
 '.',
 'The',
 'Court',
 'also',
 'directed',
 'that',
 'CEOs',
 'of',
 'Waqf',
 'Boards',
 'should',
 'preferably',
 'be',
 'Muslims',
 '.',
 'The',
 'removal',
 'of',
 'the',
 'provision',
 'for',
 'waqf-by-user',
 'recognition',
 'in',
 'the',
 'amended',
 'law',
 'has',
 'been',
 'upheld',
 'as',
 'valid',
 'by',
 'the',
 'Court',
 ',',
 'with',
 'the',
 'caveat',
 'that',
 'waqf',
 'properties',
 'registered',
 'as',
 'on',
 'April',
 '8',
 ',',
 '2025',
 ',',
 'under',
 'such',
 'a',
 'claim',
 'remain',
 'protected',
 '.',
 'Restrictions',
 'on',
 'waqf',
 'status',
 'for',
 'protected',
 'monuments',
 'and',
 'tribal',
 'lands',
 'were',
 'deemed',
 'constitutionally',
 'valid',
 '.']

In [65]:
# Applying stopwords
stop_words = set(stopwords.words('english'))
filtered_sentence = [word for word in word_tokenize(editorial) if word.lower() not in stop_words]
print("Original TEXT:")
print(mywords)
print("\nText after removing stopwords")
print(filtered_sentence)

Original TEXT:
The Supreme Court of India walked a tightrope in its judgment delivered on September 15, 2025, on the Waqf (Amendment) Act, 2025, which amended the 1995 Waqf Act to regulate Muslim religious endowments, including vast land holdings across India. The Court put several controversial provisions on hold but refused to freeze the entire Act on grounds of constitutionality and other concerns. This turned out to be a rare instance where supporters and critics of the Act claimed vindication for their respective positions in the Court’s order. The government views the amendments as necessary to curb the alleged misuse and corruption under the earlier Waqf Act, while critics, including the Congress, see it as arbitrary interference in the affairs of the Muslim community. The Court has now stayed the requirement that only Muslims practising for five years can create waqf, and the power vested in District Collectors to adjudicate waqf property disputes. It also capped non-Muslim members to four in the Central Waqf Council and three in State Boards, down from potentially 12 and seven, respectively. The Court also directed that CEOs of Waqf Boards should preferably be Muslims. The removal of the provision for waqf-by-user recognition in the amended law has been upheld as valid by the Court, with the caveat that waqf properties registered as on April 8, 2025, under such a claim remain protected. Restrictions on waqf status for protected monuments and tribal lands were deemed constitutionally valid.

Text after removing stopwords
['Supreme', 'Court', 'India', 'walked', 'tightrope', 'judgment', 'delivered', 'September', '15', ',', '2025', ',', 'Waqf', '(', 'Amendment', ')', 'Act', ',', '2025', ',', 'amended', '1995', 'Waqf', 'Act', 'regulate', 'Muslim', 'religious', 'endowments', ',', 'including', 'vast', 'land', 'holdings', 'across', 'India', '.', 'Court', 'put', 'several', 'controversial', 'provisions', 'hold', 'refused', 'freeze', 'entire', 'Act', 'grounds', 'constitutionality', 'concerns', '.', 'turned', 'rare', 'instance', 'supporters', 'critics', 'Act', 'claimed', 'vindication', 'respective', 'positions', 'Court', '’', 'order', '.', 'government', 'views', 'amendments', 'necessary', 'curb', 'alleged', 'misuse', 'corruption', 'earlier', 'Waqf', 'Act', ',', 'critics', ',', 'including', 'Congress', ',', 'see', 'arbitrary', 'interference', 'affairs', 'Muslim', 'community', '.', 'Court', 'stayed', 'requirement', 'Muslims', 'practising', 'five', 'years', 'create', 'waqf', ',', 'power', 'vested', 'District', 'Collectors', 'adjudicate', 'waqf', 'property', 'disputes', '.', 'also', 'capped', 'non-Muslim', 'members', 'four', 'Central', 'Waqf', 'Council', 'three', 'State', 'Boards', ',', 'potentially', '12', 'seven', ',', 'respectively', '.', 'Court', 'also', 'directed', 'CEOs', 'Waqf', 'Boards', 'preferably', 'Muslims', '.', 'removal', 'provision', 'waqf-by-user', 'recognition', 'amended', 'law', 'upheld', 'valid', 'Court', ',', 'caveat', 'waqf', 'properties', 'registered', 'April', '8', ',', '2025', ',', 'claim', 'remain', 'protected', '.', 'Restrictions', 'waqf', 'status', 'protected', 'monuments', 'tribal', 'lands', 'deemed', 'constitutionally', 'valid', '.']

In [66]:
print("Original TEXT:")
print(mywords)
print("\nText after removing stopwords")
print(filtered_sentence)

Original TEXT:
['The', 'Supreme', 'Court', 'of', 'India', 'walked', 'a', 'tightrope', 'in', 'its', 'judgment', 'delivered', 'on', 'September', '15', ',', '2025', ',', 'on', 'the', 'Waqf', '(', 'Amendment', ')', 'Act', ',', '2025', ',', 'which', 'amended', 'the', '1995', 'Waqf', 'Act', 'to', 'regulate', 'Muslim', 'religious', 'endowments', ',', 'including', 'vast', 'land', 'holdings', 'across', 'India', '.', 'The', 'Court', 'put', 'several', 'controversial', 'provisions', 'on', 'hold', 'but', 'refused', 'to', 'freeze', 'the', 'entire', 'Act', 'on', 'grounds', 'of', 'constitutionality', 'and', 'other', 'concerns', '.', 'This', 'turned', 'out', 'to', 'be', 'a', 'rare', 'instance', 'where', 'supporters', 'and', 'critics', 'of', 'the', 'Act', 'claimed', 'vindication', 'for', 'their', 'respective', 'positions', 'in', 'the', 'Court', '’', 's', 'order', '.', 'The', 'government', 'views', 'the', 'amendments', 'as', 'necessary', 'to', 'curb', 'the', 'alleged', 'misuse', 'and', 'corruption', 'under', 'the', 'earlier', 'Waqf', 'Act', ',', 'while', 'critics', ',', 'including', 'the', 'Congress', ',', 'see', 'it', 'as', 'arbitrary', 'interference', 'in', 'the', 'affairs', 'of', 'the', 'Muslim', 'community', '.', 'The', 'Court', 'has', 'now', 'stayed', 'the', 'requirement', 'that', 'only', 'Muslims', 'practising', 'for', 'five', 'years', 'can', 'create', 'waqf', ',', 'and', 'the', 'power', 'vested', 'in', 'District', 'Collectors', 'to', 'adjudicate', 'waqf', 'property', 'disputes', '.', 'It', 'also', 'capped', 'non-Muslim', 'members', 'to', 'four', 'in', 'the', 'Central', 'Waqf', 'Council', 'and', 'three', 'in', 'State', 'Boards', ',', 'down', 'from', 'potentially', '12', 'and', 'seven', ',', 'respectively', '.', 'The', 'Court', 'also', 'directed', 'that', 'CEOs', 'of', 'Waqf', 'Boards', 'should', 'preferably', 'be', 'Muslims', '.', 'The', 'removal', 'of', 'the', 'provision', 'for', 'waqf-by-user', 'recognition', 'in', 'the', 'amended', 'law', 'has', 'been', 'upheld', 'as', 'valid', 'by', 'the', 'Court', ',', 'with', 'the', 'caveat', 'that', 'waqf', 'properties', 'registered', 'as', 'on', 'April', '8', ',', '2025', ',', 'under', 'such', 'a', 'claim', 'remain', 'protected', '.', 'Restrictions', 'on', 'waqf', 'status', 'for', 'protected', 'monuments', 'and', 'tribal', 'lands', 'were', 'deemed', 'constitutionally', 'valid', '.']

Text after removing stopwords
['Supreme', 'Court', 'India', 'walked', 'tightrope', 'judgment', 'delivered', 'September', '15', ',', '2025', ',', 'Waqf', '(', 'Amendment', ')', 'Act', ',', '2025', ',', 'amended', '1995', 'Waqf', 'Act', 'regulate', 'Muslim', 'religious', 'endowments', ',', 'including', 'vast', 'land', 'holdings', 'across', 'India', '.', 'Court', 'put', 'several', 'controversial', 'provisions', 'hold', 'refused', 'freeze', 'entire', 'Act', 'grounds', 'constitutionality', 'concerns', '.', 'turned', 'rare', 'instance', 'supporters', 'critics', 'Act', 'claimed', 'vindication', 'respective', 'positions', 'Court', '’', 'order', '.', 'government', 'views', 'amendments', 'necessary', 'curb', 'alleged', 'misuse', 'corruption', 'earlier', 'Waqf', 'Act', ',', 'critics', ',', 'including', 'Congress', ',', 'see', 'arbitrary', 'interference', 'affairs', 'Muslim', 'community', '.', 'Court', 'stayed', 'requirement', 'Muslims', 'practising', 'five', 'years', 'create', 'waqf', ',', 'power', 'vested', 'District', 'Collectors', 'adjudicate', 'waqf', 'property', 'disputes', '.', 'also', 'capped', 'non-Muslim', 'members', 'four', 'Central', 'Waqf', 'Council', 'three', 'State', 'Boards', ',', 'potentially', '12', 'seven', ',', 'respectively', '.', 'Court', 'also', 'directed', 'CEOs', 'Waqf', 'Boards', 'preferably', 'Muslims', '.', 'removal', 'provision', 'waqf-by-user', 'recognition', 'amended', 'law', 'upheld', 'valid', 'Court', ',', 'caveat', 'waqf', 'properties', 'registered', 'April', '8', ',', '2025', ',', 'claim', 'remain', 'protected', '.', 'Restrictions', 'waqf', 'status', 'protected', 'monuments', 'tribal', 'lands', 'deemed', 'constitutionally', 'valid', '.']

# Stemming and Lemmatization

In [67]:
from nltk.stem import PorterStemmer # stemming
from nltk.stem import WordNetLemmatizer # lemmatization

In [68]:
text = "Natural Language Processing is a field of artificial intelligence that focuses on the interaction between computers and human language."
text

'Natural Language Processing is a field of artificial intelligence that focuses on the interaction between computers and human language.'

In [69]:
list_of_words = text.split(" ")
list_of_words

['Natural',
 'Language',
 'Processing',
 'is',
 'a',
 'field',
 'of',
 'artificial',
 'intelligence',
 'that',
 'focuses',
 'on',
 'the',
 'interaction',
 'between',
 'computers',
 'and',
 'human',
 'language.']

In [70]:
tokens = word_tokenize(text)
tokens

['Natural',
 'Language',
 'Processing',
 'is',
 'a',
 'field',
 'of',
 'artificial',
 'intelligence',
 'that',
 'focuses',
 'on',
 'the',
 'interaction',
 'between',
 'computers',
 'and',
 'human',
 'language',
 '.']

In [71]:
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in tokens]
print(tokens)
print("******************")
print(stemmed_words)

['Natural', 'Language', 'Processing', 'is', 'a', 'field', 'of', 'artificial', 'intelligence', 'that', 'focuses', 'on', 'the', 'interaction', 'between', 'computers', 'and', 'human', 'language', '.']
******************
['natur', 'languag', 'process', 'is', 'a', 'field', 'of', 'artifici', 'intellig', 'that', 'focus', 'on', 'the', 'interact', 'between', 'comput', 'and', 'human', 'languag', '.']

# Lemmatization

In [77]:
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
lemmatizer_words = [lemmatizer.lemmatize(word) for word in tokens]
print(tokens)
print("******************")
print(lemmatizer_words)

['Natural', 'Language', 'Processing', 'is', 'a', 'field', 'of', 'artificial', 'intelligence', 'that', 'focuses', 'on', 'the', 'interaction', 'between', 'computers', 'and', 'human', 'language', '.']
******************
['Natural', 'Language', 'Processing', 'is', 'a', 'field', 'of', 'artificial', 'intelligence', 'that', 'focus', 'on', 'the', 'interaction', 'between', 'computer', 'and', 'human', 'language', '.']

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!